server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10000000
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ComputerManagement;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mail:
    host: smtp.gmail.com
    port: 587
    username: thaotruong23082004@gmail.com
    password: nxxj lejr iova juux
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
  
  jmx:
    enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

api:
  prefix: api/v1

jwt:
  expiration: 3600 #60 minutes = 60 * 60
  secretKey: xGOnTfLD3SjBwuK6pUYJMynjaJ/rksW/ItheskdThnc=

