server:
  port: 8088
  tomcat:
    max-http-post-size: 10000000
spring:
  datasource:
    #    url: jdbc:mysql://clothingstore.mysql.database.azure.com:3306/ClothingStore?useSSL=true&serverTimezone=UTC
    #    username: ducthang
    #    password: 'Thang@3008'
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:sqlserver://localhost:1433;databaseName=ComputerManagement;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ducthang30082004@gmail.com
    password: xyjo iidy wmqj vfco
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

api:
  prefix: api/v1

jwt:
  expiration: 3600 #60 minutes = 60 * 60
  secretKey: xGOnTfLD3SjBwuK6pUYJMynjaJ/rksW/ItheskdThnc=